baseURL = "https://mrdee.in/"
languageCode = "en-us"
<<<<<<< HEAD
title = "Mr.Dee Notes"
=======
title = "Mr.Dee's Notes"
>>>>>>> a03e3cf491753a7f3dd98a80dfb8c63b90b35252
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  description = "Daily Notes"
  author = "Mr.Dee"

  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  TocOpen = false

  defaultTheme = "auto"

[menu]
  [[menu.main]]
    name = "Curl Notes"
    url = "/curl-notes/"
    weight = 1

  [[menu.main]]
    name = "Reading"
    url = "/reading/"
    weight = 2

  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 3
